image: alpine:latest

variables:
  HEROKU_APP_NAME: reddio-next

stages:
  - build
  - e2e

job_build_cljs:
  image: clojure:lein-2.7.1
  stage: build
  except:
    - master
  script:
    - lein cljsbuild once min
  artifacts:
    paths:
      - resources/public/js/compiled

job_build_js:
  image: node:6.10.0
  stage: build
  except:
    - master
  script:
    - ./scripts/install-yarn.sh
    - yarn install
    - npm run frontend:build
  artifacts:
    paths:
      - resources/public/js/compiled
      - resources/public/css/compiled

job_e2e:
  stage: e2e
  except:
    - master
  script:
    - cd resources/public/js && ls -la
  artifacts:
    paths:
      - resources/public
