[Settings]
  ID = "not-a-real-id"

[build]
  base = "."
  publish = ""
  command = ""

[context.production]
  publish = ""
  command = ""

[context.deploy-preview]
  publish = ""
  command = ""

[context.branch-deploy]
  publish = ""
  command = ""
