apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $APP_NAME
  namespace: $KUBE_NAMESPACE
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: $IMAGE_TAG
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
