apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  namespace: $KUBE_NAMESPACE
  labels:
    run: $APP_NAME
spec:
  type: LoadBalancer
  selector:
    run: $APP_NAME
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
